import React from "react";

const MainInvestmentList = () => {
  return (
    <>
      <tr>
        <th>1</th>
        <td>पिछली उधारी/नामे / previous loan/debit</td>
        <td>
          <input
            type="date"
            name="date"
            value="2021-08-01"
            readOnly
            className="semiSmallInput"
          />
        </td>
        <td>
          <input
            type="number"
            name="price"
            value={162000}
            readOnly
            className="semiSmallInput"
          />
        </td>
      </tr>
      <tr>
        <th>2</th>
        <td>सामान/ Belonging</td>
        <td>
          <input
            type="date"
            name="date"
            value="2021-08-01"
            readOnly
            className="semiSmallInput"
          />
        </td>
        <td>
          <input
            type="number"
            name="price"
            value={162000}
            readOnly
            className="semiSmallInput"
          />
        </td>
      </tr>
      <tr>
        <th>3</th>
        <td>सामान/ Belonging</td>
        <td>
          <input
            type="date"
            name="date"
            value="2021-08-01"
            readOnly
            className="semiSmallInput"
          />
        </td>
        <td>
          <input
            type="number"
            name="price"
            value={162000}
            readOnly
            className="semiSmallInput"
          />
        </td>
      </tr>
      <tr>
        <th>4</th>
        <td>सामान/ Belonging</td>
        <td>
          <input
            type="date"
            name="date"
            value="2021-08-01"
            readOnly
            className="semiSmallInput"
          />
        </td>
        <td>
          <input
            type="number"
            name="price"
            value={162000}
            readOnly
            className="semiSmallInput"
          />
        </td>
      </tr>
      <tr>
        <th>5</th>
        <td>फीस / Fees</td>
        <td>
          <input
            type="date"
            name="date"
            value="2021-08-01"
            readOnly
            className="semiSmallInput"
          />
        </td>
        <td>
          <input
            type="number"
            name="price"
            value={162000}
            readOnly
            className="semiSmallInput"
          />
        </td>
      </tr>
      <tr>
        <th>6</th>
        <td>फीस / Feest</td>
        <td>
          <input
            type="date"
            name="date"
            value="2021-08-01"
            readOnly
            className="semiSmallInput"
          />
        </td>
        <td>
          <input
            type="number"
            name="price"
            value={162000}
            readOnly
            className="semiSmallInput"
          />
        </td>
      </tr>
      <tr>
        <th>7</th>
        <td>फीस / Fees</td>
        <td>
          <input
            type="date"
            name="date"
            value="2021-08-01"
            readOnly
            className="semiSmallInput"
          />
        </td>
        <td>
          <input
            type="number"
            name="price"
            value={162000}
            readOnly
            className="semiSmallInput"
          />
        </td>
      </tr>
      <tr>
        <th>8</th>
        <td>माल पेटे व रिजर्व रकम/ freight and reserve amount</td>
        <td>
          <input
            type="date"
            name="date"
            value="2021-08-01"
            readOnly
            className="semiSmallInput"
          />
        </td>
        <td>
          <input
            type="number"
            name="price"
            value={162000}
            readOnly
            className="semiSmallInput"
          />
        </td>
      </tr>
      <tr>
        <th>10</th>
        <td>नकद गल्ले में / cash in hand</td>
        <td>
          <input
            type="date"
            name="date"
            value="2021-08-01"
            readOnly
            className="semiSmallInput"
          />
        </td>
        <td>
          <input
            type="number"
            name="price"
            value={162000}
            readOnly
            className="semiSmallInput"
          />
        </td>
      </tr>
    </>
  );
};

export default MainInvestmentList;
